version: '3.8'

# Описываем сервисы (контейнеры), которые мы хотим запустить.
services:
  # Наш сервис приложения.
  app:
    # Собирать образ из Dockerfile в текущей директории.
    build: .
    ports:
      # Пробрасываем порт 3000 из контейнера на порт 3000 нашей машины.
      - "3000:3000"
    # Указываем, какой файл использовать для переменных окружения.
    # Мы используем .env.example, т.к. в нем правильные настройки для Docker-сети.
    env_file:
      - .env.example
    # Запускать этот сервис только после того, как запустится сервис 'redis'.
    depends_on:
      - redis
    # Перезапускать контейнер, если он упал, но не при остановке Docker.
    restart: unless-stopped

  # Сервис базы данных Redis.
  redis:
    # Используем официальный легковесный образ Redis.
    image: "redis:alpine"
    # Всегда перезапускать, если он упал.
    restart: always
    # Нам не нужно пробрасывать порт Redis наружу, т.к. сервис 'app'
    # будет общаться с ним по внутренней сети Docker.